### ISSUE TITLE
Its own subdirectory but hardcoded paths

### ISSUE THREAD

**Issue by Akuukis** [TooAngel/screeps-server-bot-mod#1]
I got it working.

But I would like to put it in its own subdirectory, for example `mods/botTooAngel`, but it has hardcoded paths that doesn't let me do so.

**Comment by ags131** [comment]
A note, you can replace that hardcoded path with 'lodash' then just `npm install --save lodash`, that way anyone installing can just `npm install` in the directory or install via NPM if published

**Comment by TooAngel** [comment]
Sorry, I someone missed this issue and the notification. I adapted the code to get rid of the hardcoded path, but due to the official server bot implementation, I think this is mod is useless.
Anyway thank you for using and looking into.
